trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: billing-api
  acrName: billingacr123
  resourceGroup: billing-rg
  aksCluster: billing-aks

steps:

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'ACR-ServiceConnection'
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: backend/billing-api/dockerfile
    tags: |
      latest

- task: Kubernetes@1
  displayName: Deploy to AKS
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: 'Azure-ServiceConnection'
    azureResourceGroup: $(resourceGroup)
    kubernetesCluster: $(aksCluster)
    command: apply
    useConfigurationFile: true
    configuration: k8s/