apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-api
  template:
    metadata:
      labels:
        app: billing-api
    spec:
      containers:
      - name: billing-api
        image: billingacr123.azurecr.io/billing-api:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: billing-api-service
spec:
  type: ClusterIP
  selector:
    app: billing-api
  ports:
  - port: 80
    targetPort: 8080